apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-nginx-site
data:
  index.html: |
    <html>
      <body style="font-family: Arial">
        <h2>Edge Nginx - Akuity Takehome</h2>
        <p>Deployed by Argo CD, promoted by Kargo.</p>
      </body>
    </html>
