apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-nginx
  template:
    metadata:
      labels:
        app: edge-nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.26.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: site
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site
        configMap:
          name: edge-nginx-site
