apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: edge-promo
  namespace: edge-promo
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: false
    - stage: prod
      autoPromotionEnabled: false
